### PR TITLE
[Tests] ses-compat - create polyfill wrapper if using intrinsic Object.assign

### PR DESCRIPTION
**Pull request by kumavis**
the issue is that when `Object.assign` is present, this package appends additional properties to it, like `getPolyfill`. under SES, this has been hardened and you cannot append the properties

### CODE REVIEW

**Comment by kumavis** [comment]
some tests from `es-shim-api` fails

**Comment by kumavis** [comment]
```
not ok 3 module.exports === getPolyfill()
not ok 10 shim returns polyfill (pass `--skip-shim-returns-polyfill` to skip this test)
```

**Comment by kumavis** [comment]
ok it works :+1:

**Comment by kumavis** [comment]
@ljharb ready for review

**Comment by ljharb** [comment]
Rather than alter the `getPolyfill` result - for which it's important it's `===` to `Object.assign` as often as possible - I've updated this PR to wrap the `index.js` entrypoint instead.

**Comment by kumavis** [comment]
sounds good but hold up some of my commits got lost

**Comment by kumavis** [comment]
so i like your version but it doesnt pass tests

**Comment by ljharb** [comment]
Looking into it.

**Comment by kumavis** [comment]
tests pass here https://github.com/ljharb/object.assign/pull/78

**Comment by kumavis** [comment]
I like your approach, and expect your tests to pass :+1:

**Comment by ljharb** [comment]
Looks like ses fails in node < 4 due to its use of `const`, and node < 12 due to its use of globalThis, which is disappointing. I'll try a tweaked approach.

**Review by ljharb — APPROVED** [review]

**Comment by ljharb** [comment]
v4.1.1 is released.

**Pull request merged**
